import { readFile, writeFile, appendFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

const BASE=process.env.BINANCE_BASE||'https://data-api.binance.vision/api/v3';
const MAX_BARS=Number(process.env.GENESIS_EDGE_BARS||5000);
const FEE=.0004,SLIP=.00015,FUNDING=.0001,HOLDOUT=.8,MAX_FAMILY_AUDITS=3;
const SESSIONS={ALL:h=>true,ASIA:h=>h>=0&&h<7,LONDON:h=>h>=7&&h<12,NY:h=>h>=13&&h<17,LONDON_NY:h=>h>=12&&h<16};
const arg=(n,f=null)=>{const i=process.argv.indexOf(n);return i>=0?(process.argv[i+1]??f):f;};
const round=(v,d=4)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const std=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1));};
const tfMin=tf=>tf.endsWith('m')?+tf.slice(0,-1):tf.endsWith('h')?+tf.slice(0,-1)*60:60;
async function readJson(path,fallback){try{return JSON.parse(await readFile(path,'utf8'));}catch{return fallback;}}
async function fetchHistory(pair,tf){const all=[];let end=Date.now();while(all.length<MAX_BARS){const limit=Math.min(1000,MAX_BARS-all.length),r=await fetch(`${BASE}/klines?symbol=${pair}&interval=${tf}&limit=${limit}&endTime=${end}`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`binance_${r.status}:${pair}:${tf}`);const p=await r.json();if(!Array.isArray(p)||!p.length)break;all.unshift(...p);const first=+p[0][0];if(!Number.isFinite(first)||p.length<limit)break;end=first-1;await new Promise(x=>setTimeout(x,30));}return [...new Map(all.map(x=>[+x[0],x])).values()].sort((a,b)=>+a[0]-+b[0]).slice(-MAX_BARS);}
function prepare(rows,periods){const c=rows.map(r=>+r[4]),h=rows.map(r=>+r[2]),l=rows.map(r=>+r[3]),ma=new Map(),atr=[],volRatio=[];for(const p of new Set([8,20,34,55,200,...periods])){const arr=[];let sum=0;for(let i=0;i<c.length;i++){sum+=c[i];if(i>=p)sum-=c[i-p];arr[i]=i>=p-1?sum/p:null;}ma.set(p,arr);}for(let i=0;i<c.length;i++){if(i<14){atr[i]=null;volRatio[i]=null;continue;}let tr=0;for(let j=i-13;j<=i;j++)tr+=Math.max(h[j]-l[j],Math.abs(h[j]-c[j-1]),Math.abs(l[j]-c[j-1]));atr[i]=(tr/14)/c[i];if(i<62){volRatio[i]=null;continue;}const recent=[],base=[];for(let j=i-23;j<=i;j++)recent.push(Math.log(c[j]/c[j-1]));for(let j=i-61;j<=i-24;j++)base.push(Math.log(c[j]/c[j-1]));const rv=std(recent),bv=std(base);volRatio[i]=bv>0?rv/bv:null;}return{c,ma,atr,volRatio};}
function signal(spec,rows,p,i){if(i<210||!SESSIONS[spec.session])return null;const hour=new Date(+rows[i][0]).getUTCHours();if(!SESSIONS[spec.session](hour))return null;const c=p.c[i],prev=p.c[i-1],m8=p.ma.get(8)?.[i],m55=p.ma.get(55)?.[i],m200=p.ma.get(200)?.[i],vr=p.volRatio[i];if(![c,prev,m8,m55,m200,vr].every(Number.isFinite))return null;if(spec.family==='opening_range_breakout'){let hi=-Infinity,lo=Infinity;for(let j=i-spec.period;j<i;j++){hi=Math.max(hi,p.c[j]);lo=Math.min(lo,p.c[j]);}if(vr>1&&c>hi&&c>m55)return'LONG';if(vr>1&&c<lo&&c<m55)return'SHORT';}if(spec.family==='trend_pullback'){if(c>m55&&m55>m200&&prev<=p.ma.get(8)[i-1]&&c>m8&&vr>.8&&vr<1.5)return'LONG';if(c<m55&&m55<m200&&prev>=p.ma.get(8)[i-1]&&c<m8&&vr>.8&&vr<1.5)return'SHORT';}if(spec.family==='volatility_squeeze'){if(vr>=.75)return null;let hi=-Infinity,lo=Infinity;for(let j=i-spec.period;j<i;j++){hi=Math.max(hi,p.c[j]);lo=Math.min(lo,p.c[j]);}if(c>hi&&c>m55)return'LONG';if(c<lo&&c<m55)return'SHORT';}if(spec.family==='failed_breakout'){if(vr<1.15)return null;let hi=-Infinity,lo=Infinity;for(let j=i-spec.period;j<i-1;j++){hi=Math.max(hi,p.c[j]);lo=Math.min(lo,p.c[j]);}if(prev>hi&&c<hi)return'SHORT';if(prev<lo&&c>lo)return'LONG';}return null;}
function simulate(rows,prep,market,spec){const trades=[];let last=-1;const mins=tfMin(market.tf);for(let i=210;i<rows.length-2;i++){if(i<=last)continue;const side=signal(spec,rows,prep,i);if(!side)continue;const a=prep.atr[i];if(!(a>0))continue;const ei=i+1,re=+rows[ei][1],entry=side==='LONG'?re*(1+SLIP):re*(1-SLIP),tp=Math.max(.001,a*spec.targetAtr),sp=Math.max(.001,a*spec.stopAtr),target=side==='LONG'?entry*(1+tp):entry*(1-tp),stop=side==='LONG'?entry*(1-sp):entry*(1+sp);let xi=Math.min(rows.length-1,ei+spec.timeoutBars),rx=+rows[xi][4];for(let j=ei;j<=xi;j++){const hh=+rows[j][2],ll=+rows[j][3],sh=side==='LONG'?ll<=stop:hh>=stop,th=side==='LONG'?hh>=target:ll<=target;if(sh){xi=j;rx=stop;break;}if(th){xi=j;rx=target;break;}}const exit=side==='LONG'?rx*(1-SLIP):rx*(1+SLIP),gross=side==='LONG'?(exit-entry)/entry:(entry-exit)/entry,held=Math.max(mins/60,(xi-ei+1)*mins/60),net=gross-(FEE*2+FUNDING*held/8);trades.push({relativeIndex:ei/rows.length,netPct:net});last=xi;}return trades;}
function metrics(t){const p=t.map(x=>x.netPct),wins=p.filter(x=>x>0),losses=p.filter(x=>x<0),gp=wins.reduce((s,x)=>s+x,0),gl=Math.abs(losses.reduce((s,x)=>s+x,0)),ev=p.length?mean(p):null,sd=std(p),ts=p.length>1&&sd>0&&ev!=null?ev/(sd/Math.sqrt(p.length)):null;let curve=0,peak=0,dd=0;for(const x of p){curve+=x;peak=Math.max(peak,curve);dd=Math.max(dd,peak-curve);}return{trades:p.length,expectancyBps:ev==null?null:round(ev*10000,2),profitFactor:gl>0?round(gp/gl,3):null,tStat:round(ts,3),maxDrawdownPct:round(dd*100,2)};}
function auditPass(m){return m.trades>=8&&(m.expectancyBps??-999)>0&&(m.profitFactor??0)>=1.1&&(m.tStat??-999)>=.75&&(m.maxDrawdownPct??999)<=12;}
function rejectReason(m){if((m.trades??0)<8)return'INSUFFICIENT_HOLDOUT_SAMPLE';if((m.expectancyBps??-999)<=0)return'NEGATIVE_HOLDOUT_EXPECTANCY';if((m.profitFactor??0)<1.1)return'WEAK_HOLDOUT_PROFIT_FACTOR';if((m.tStat??-999)<.75)return'LOW_HOLDOUT_TSTAT';if((m.maxDrawdownPct??999)>12)return'HOLDOUT_DRAWDOWN';return'AUDIT_GATE_NOT_MET';}
function familyState(ledger,key){return ledger.familyStats[key]??{audits:0,passes:0,rejects:0,reasons:{},status:'OPEN'};}

async function main(){
  const adaptivePath=arg('--adaptive','quant-evidence/edge-adaptive-latest.json'),ledgerPath=arg('--ledger','quant-evidence/edge-audit-ledger.json'),out=arg('--out','quant-evidence/edge-audit-latest.json'),history=arg('--history','quant-evidence/edge-audit-history.jsonl');
  const adaptive=JSON.parse(await readFile(adaptivePath,'utf8'));if(adaptive.paperOnly!==true||adaptive.liveOrders!==false||adaptive.executionAuthority!==false||adaptive.capitalEligible!==false)throw new Error('adaptive_boundary_unverified');
  const priorSnapshot=await readJson(out,null);
  const ledger=await readJson(ledgerPath,{version:'edge_audit_ledger_v3_family_budget',auditedIds:[],passedCandidates:{},familyStats:{}});ledger.version='edge_audit_ledger_v3_family_budget';ledger.auditedIds=ledger.auditedIds??[];ledger.passedCandidates=ledger.passedCandidates??{};ledger.familyStats=ledger.familyStats??{};
  for(const r of priorSnapshot?.results??[]){if(r?.status==='PAPER_RESEARCH_CANDIDATE'&&r.id&&!ledger.passedCandidates[r.id])ledger.passedCandidates[r.id]={...r,migratedFromPriorSnapshot:true};}
  const audited=new Set(ledger.auditedIds);
  const incoming=(adaptive.auditQueue??[]).filter(x=>!audited.has(x.id)).filter(x=>{
    const key=x.hypothesisKey??'UNKNOWN';const fs=familyState(ledger,key);return fs.passes>0||fs.audits<MAX_FAMILY_AUDITS;
  }).slice(0,3),results=[];
  if(incoming.length){
    const keys=[...new Set(incoming.map(x=>`${x.market.pair}:${x.market.tf}`))],datasets=new Map();
    for(const key of keys){const [pair,tf]=key.split(':'),items=incoming.filter(x=>x.market.pair===pair&&x.market.tf===tf),rows=await fetchHistory(pair,tf);datasets.set(key,{rows,prep:prepare(rows,items.map(x=>x.spec.period)),market:{pair,tf}});}
    for(const item of incoming){
      const d=datasets.get(`${item.market.pair}:${item.market.tf}`),tr=simulate(d.rows,d.prep,d.market,item.spec),holdout=metrics(tr.filter(x=>x.relativeIndex>=HOLDOUT)),pass=auditPass(holdout),reason=pass?null:rejectReason(holdout),key=item.hypothesisKey??'UNKNOWN';
      const result={id:item.id,hypothesisKey:key,market:item.market,spec:item.spec,parentVariant:item.parentVariant,selectionScore:item.selectionScore,holdout,status:pass?'PAPER_RESEARCH_CANDIDATE':'AUDIT_REJECTED',rejectReason:reason,auditedAt:new Date().toISOString()};
      results.push(result);audited.add(item.id);
      const fs=familyState(ledger,key);fs.audits++;if(pass){fs.passes++;fs.status='PASSED';ledger.passedCandidates[item.id]=result;}else{fs.rejects++;fs.reasons[reason]=(fs.reasons[reason]??0)+1;if(fs.passes===0&&fs.audits>=MAX_FAMILY_AUDITS)fs.status='AUDIT_BUDGET_EXHAUSTED';}fs.updatedAt=result.auditedAt;ledger.familyStats[key]=fs;
    }
  }
  const exhausted=Object.entries(ledger.familyStats).filter(([,v])=>v.status==='AUDIT_BUDGET_EXHAUSTED').map(([key])=>key);
  const passed=results.filter(x=>x.status==='PAPER_RESEARCH_CANDIDATE'),snapshot={ok:true,version:'edge_one_shot_audit_v3_family_budget',mode:'RESEARCH_ONLY',paperOnly:true,liveOrders:false,executionAuthority:false,capitalEligible:false,completedAt:new Date().toISOString(),methodology:{oneShot:true,holdoutStart:HOLDOUT,maxAuditsPerUnprovenFamily:MAX_FAMILY_AUDITS,gate:{minTrades:8,minExpectancyBps:0,minProfitFactor:1.1,minTStat:.75,maxDrawdownPct:12},durablePassedRegistry:true,familyAuditBudget:true},sourceAdaptiveCompletedAt:adaptive.completedAt??null,newAudits:results.length,passed:passed.length,totalPassedRegistered:Object.keys(ledger.passedCandidates).length,exhaustedFamilies:exhausted,verdict:passed.length?'PAPER_RESEARCH_CANDIDATE_FOUND':results.length?'AUDIT_REJECTED':'NO_NEW_AUDIT_CANDIDATES',results};
  ledger.updatedAt=snapshot.completedAt;ledger.auditedIds=[...audited];await mkdir(dirname(out),{recursive:true});await writeFile(out,JSON.stringify(snapshot,null,2)+'\n');await appendFile(history,JSON.stringify(snapshot)+'\n');await writeFile(ledgerPath,JSON.stringify(ledger,null,2)+'\n');console.log(JSON.stringify({ok:true,verdict:snapshot.verdict,newAudits:snapshot.newAudits,passed:snapshot.passed,exhaustedFamilies:snapshot.exhaustedFamilies.length}));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
