import { mkdir, readFile, writeFile, appendFile } from 'node:fs/promises';
import { dirname } from 'node:path';

const VERSION='edge_factory_v3_expanded_universe';
const BASE=process.env.BINANCE_BASE||'https://data-api.binance.vision/api/v3';
const MAX_BARS=Number(process.env.GENESIS_EDGE_BARS||5000);
const FEE=.0004,SLIP=.00015,FUNDING=.0001,TRAIN=.6,VALID=.8;
const SYMBOLS=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT'];
const TIMEFRAMES=['15m','30m','1h','4h'];
const MARKETS=SYMBOLS.flatMap(pair=>TIMEFRAMES.map(tf=>({pair,tf})));
const SESSIONS={ALL:h=>true,ASIA:h=>h>=0&&h<7,LONDON:h=>h>=7&&h<12,NY:h=>h>=13&&h<17,LONDON_NY:h=>h>=12&&h<16};
const SPECS=[
  {family:'trend_pullback',periods:[20,55],targetAtr:[1.5,2],stopAtr:[.75],timeoutBars:[8],sessions:['ALL','ASIA','LONDON_NY']},
  {family:'opening_range_breakout',periods:[12,20],targetAtr:[1.5,2],stopAtr:[.75],timeoutBars:[8],sessions:['ASIA','LONDON','NY']},
  {family:'volatility_squeeze',periods:[20,34],targetAtr:[1.5,2],stopAtr:[.75],timeoutBars:[8],sessions:['ALL','ASIA','NY']},
  {family:'failed_breakout',periods:[20,34],targetAtr:[1,1.5],stopAtr:[.75],timeoutBars:[8],sessions:['ALL','ASIA','LONDON_NY']},
];
const round=(v,d=4)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const std=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1));};
const tfMin=tf=>tf.endsWith('m')?+tf.slice(0,-1):tf.endsWith('h')?+tf.slice(0,-1)*60:60;
const arg=(n,f=null)=>{const i=process.argv.indexOf(n);return i>=0?(process.argv[i+1]??f):f;};

async function fetchHistory(pair,tf){const all=[];let end=Date.now();while(all.length<MAX_BARS){const limit=Math.min(1000,MAX_BARS-all.length);const r=await fetch(`${BASE}/klines?symbol=${pair}&interval=${tf}&limit=${limit}&endTime=${end}`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`binance_${r.status}:${pair}:${tf}`);const p=await r.json();if(!Array.isArray(p)||!p.length)break;all.unshift(...p);const first=+p[0][0];if(!Number.isFinite(first)||p.length<limit)break;end=first-1;await new Promise(x=>setTimeout(x,30));}const rows=[...new Map(all.map(x=>[+x[0],x])).values()].sort((a,b)=>+a[0]-+b[0]).slice(-MAX_BARS);if(rows.length<1000)throw new Error(`insufficient:${pair}:${tf}`);return rows;}
function prepare(rows){const c=rows.map(r=>+r[4]),h=rows.map(r=>+r[2]),l=rows.map(r=>+r[3]);const ma8=[],ma20=[],ma34=[],ma55=[],ma200=[],atr=[],volRatio=[];const roll=(p,i)=>i<p-1?null:c.slice(i-p+1,i+1).reduce((s,x)=>s+x,0)/p;for(let i=0;i<c.length;i++){ma8[i]=roll(8,i);ma20[i]=roll(20,i);ma34[i]=roll(34,i);ma55[i]=roll(55,i);ma200[i]=roll(200,i);if(i<14){atr[i]=null;volRatio[i]=null;continue;}let tr=0;for(let j=i-13;j<=i;j++)tr+=Math.max(h[j]-l[j],Math.abs(h[j]-c[j-1]),Math.abs(l[j]-c[j-1]));atr[i]=(tr/14)/c[i];if(i<62){volRatio[i]=null;continue;}const recent=[],base=[];for(let j=i-23;j<=i;j++)recent.push(Math.log(c[j]/c[j-1]));for(let j=i-61;j<=i-24;j++)base.push(Math.log(c[j]/c[j-1]));const rv=std(recent),bv=std(base);volRatio[i]=bv>0?rv/bv:null;}return{c,ma8,ma20,ma34,ma55,ma200,atr,volRatio};}
function maFor(p,prep,i){return p===20?prep.ma20[i]:p===34?prep.ma34[i]:p===55?prep.ma55[i]:null;}
function signal(spec,rows,p,i){if(i<210)return null;const hour=new Date(+rows[i][0]).getUTCHours();if(!SESSIONS[spec.session](hour))return null;const c=p.c[i],prev=p.c[i-1],ma=maFor(spec.period,p,i)||p.ma20[i],m55=p.ma55[i],m200=p.ma200[i],vr=p.volRatio[i];if(![c,prev,ma,m55,m200,vr].every(Number.isFinite))return null;if(spec.family==='trend_pullback'){if(c>m55&&m55>m200&&prev<=p.ma8[i-1]&&c>p.ma8[i]&&vr>.8&&vr<1.5)return'LONG';if(c<m55&&m55<m200&&prev>=p.ma8[i-1]&&c<p.ma8[i]&&vr>.8&&vr<1.5)return'SHORT';}if(spec.family==='opening_range_breakout'){let hi=-Infinity,lo=Infinity;for(let j=i-spec.period;j<i;j++){hi=Math.max(hi,p.c[j]);lo=Math.min(lo,p.c[j]);}if(vr>1&&c>hi&&c>m55)return'LONG';if(vr>1&&c<lo&&c<m55)return'SHORT';}if(spec.family==='volatility_squeeze'){if(vr>=.75)return null;let hi=-Infinity,lo=Infinity;for(let j=i-spec.period;j<i;j++){hi=Math.max(hi,p.c[j]);lo=Math.min(lo,p.c[j]);}if(c>hi&&c>m55)return'LONG';if(c<lo&&c<m55)return'SHORT';}if(spec.family==='failed_breakout'){if(vr<1.15)return null;let hi=-Infinity,lo=Infinity;for(let j=i-spec.period;j<i-1;j++){hi=Math.max(hi,p.c[j]);lo=Math.min(lo,p.c[j]);}if(prev>hi&&c<hi)return'SHORT';if(prev<lo&&c>lo)return'LONG';}return null;}
function simulate(rows,prep,market,spec){const trades=[];let last=-1;const mins=tfMin(market.tf);for(let i=210;i<rows.length-2;i++){if(i<=last)continue;const side=signal(spec,rows,prep,i);if(!side)continue;const a=prep.atr[i];if(!(a>0))continue;const ei=i+1,re=+rows[ei][1];const entry=side==='LONG'?re*(1+SLIP):re*(1-SLIP);const tp=Math.max(.001,a*spec.targetAtr),sp=Math.max(.001,a*spec.stopAtr),target=side==='LONG'?entry*(1+tp):entry*(1-tp),stop=side==='LONG'?entry*(1-sp):entry*(1+sp);let xi=Math.min(rows.length-1,ei+spec.timeoutBars),rx=+rows[xi][4];for(let j=ei;j<=xi;j++){const hh=+rows[j][2],ll=+rows[j][3],sh=side==='LONG'?ll<=stop:hh>=stop,th=side==='LONG'?hh>=target:ll<=target;if(sh){xi=j;rx=stop;break;}if(th){xi=j;rx=target;break;}}const exit=side==='LONG'?rx*(1-SLIP):rx*(1+SLIP),gross=side==='LONG'?(exit-entry)/entry:(entry-exit)/entry,held=Math.max(mins/60,(xi-ei+1)*mins/60),net=gross-(FEE*2+FUNDING*held/8);trades.push({relativeIndex:ei/rows.length,netPct:net});last=xi;}return trades;}
function metrics(t){const p=t.map(x=>x.netPct),w=p.filter(x=>x>0),lo=p.filter(x=>x<0),gp=w.reduce((s,x)=>s+x,0),gl=Math.abs(lo.reduce((s,x)=>s+x,0)),ev=p.length?mean(p):null,sd=std(p),ts=p.length>1&&sd>0&&ev!=null?ev/(sd/Math.sqrt(p.length)):null;let curve=0,peak=0,dd=0;for(const x of p){curve+=x;peak=Math.max(peak,curve);dd=Math.max(dd,peak-curve);}return{trades:p.length,expectancyBps:ev==null?null:round(ev*10000,2),profitFactor:gl>0?round(gp/gl,3):null,tStat:round(ts,3),maxDrawdownPct:round(dd*100,2)};}
function walk(tr){const folds=[[0,.2],[.2,.4],[.4,.6],[.6,.8]].map(([s,e])=>metrics(tr.filter(x=>x.relativeIndex>=s&&x.relativeIndex<e)));const positiveFolds=folds.filter(m=>m.trades>=4&&(m.expectancyBps??-999)>0&&(m.profitFactor??0)>=1).length;return{positiveFolds,requiredPositiveFolds:3,pass:positiveFolds>=3};}
function classify(a,b,c,w){const positive=x=>(x.expectancyBps??-999)>0&&(x.profitFactor??0)>=1;const paper=a.trades>=20&&b.trades>=8&&c.trades>=8&&positive(a)&&(b.expectancyBps??-999)>0&&(c.expectancyBps??-999)>0&&(b.profitFactor??0)>=1.15&&(c.profitFactor??0)>=1.1&&(c.tStat??-999)>=.75&&c.maxDrawdownPct<=12&&w.pass;if(paper)return'PAPER_CANDIDATE';if(a.trades>=15&&b.trades>=6&&positive(a)&&(b.expectancyBps??-999)>0&&(b.profitFactor??0)>=1.05)return'INTERESTING';if(a.trades>=15&&b.trades>=6&&!positive(a)&&(b.expectancyBps??-999)>0&&(b.profitFactor??0)>=1.05)return'REGIME_DIVERGENCE';return'DEAD';}
function failureReason(a,b,c,w){if(a.trades<15||b.trades<6)return'INSUFFICIENT_SAMPLE';if((a.expectancyBps??-999)<=0)return'NEGATIVE_TRAIN_EXPECTANCY';if((b.expectancyBps??-999)<=0)return'NEGATIVE_VALIDATION_EXPECTANCY';if((c.expectancyBps??-999)<=0)return'NEGATIVE_HOLDOUT_EXPECTANCY';if((b.profitFactor??0)<1.05)return'WEAK_VALIDATION_PROFIT_FACTOR';if((c.profitFactor??0)<1.1)return'WEAK_HOLDOUT_PROFIT_FACTOR';if(!w.pass)return'UNSTABLE_WALK_FORWARD';if((c.tStat??-999)<.75)return'LOW_HOLDOUT_TSTAT';return'GATE_NOT_MET';}
function grid(){const out=[];for(const f of SPECS)for(const period of f.periods)for(const targetAtr of f.targetAtr)for(const stopAtr of f.stopAtr)for(const timeoutBars of f.timeoutBars)for(const session of f.sessions)out.push({family:f.family,period,targetAtr,stopAtr,timeoutBars,session});return out;}
const hypothesisKey=(s,m)=>`${s.family}:${m.pair}:${m.tf}:${s.session}`;
const variantKey=(s,m)=>`${hypothesisKey(s,m)}:p${s.period}:ta${s.targetAtr}:sa${s.stopAtr}:tb${s.timeoutBars}`;
async function memory(path){try{const lines=(await readFile(path,'utf8')).trim().split('\n').filter(Boolean).slice(-3).map(JSON.parse),m=new Map();for(const snap of lines)for(const r of snap.results??[])if(r.status==='DEAD')m.set(r.variantKey,(m.get(r.variantKey)||0)+1);return m;}catch{return new Map();}}
function learningRules(results){const groups=new Map();for(const r of results){const g=groups.get(r.hypothesisKey)||{hypothesisKey:r.hypothesisKey,total:0,interesting:0,regimeDivergence:0,paper:0,reasons:{}};g.total++;if(r.status==='INTERESTING')g.interesting++;if(r.status==='REGIME_DIVERGENCE')g.regimeDivergence++;if(r.status==='PAPER_CANDIDATE')g.paper++;if(r.failureReason)g.reasons[r.failureReason]=(g.reasons[r.failureReason]||0)+1;groups.set(r.hypothesisKey,g);}return [...groups.values()].map(g=>{const reason=Object.entries(g.reasons).sort((a,b)=>b[1]-a[1])[0]?.[0]??null;let action='DEPRIORITIZE';if(g.paper>0)action='PROMOTE_TO_FORWARD_PAPER';else if(g.interesting>0)action='MUTATE_AND_RETEST';else if(g.regimeDivergence>0)action='RETEST_ONLY_IF_REGIME_CHANGES';return{...g,dominantFailure:reason,action};}).sort((a,b)=>(b.paper-a.paper)||(b.interesting-a.interesting)||(b.regimeDivergence-a.regimeDivergence));}

async function main(){const out=arg('--out','quant-evidence/edge-factory-latest.json'),hist=arg('--history','quant-evidence/edge-factory-history.jsonl'),learningOut=arg('--learning','quant-evidence/edge-learning-latest.json'),learningHist=arg('--learning-history','quant-evidence/edge-learning-history.jsonl'),fails=await memory(hist),datasets=[];for(const market of MARKETS){const rows=await fetchHistory(market.pair,market.tf);datasets.push({market,rows,prep:prepare(rows)});}const results=[];for(const spec of grid())for(const d of datasets){const hk=hypothesisKey(spec,d.market),vk=variantKey(spec,d.market),failureStreak=fails.get(vk)||0;if(failureStreak>=3){results.push({hypothesisKey:hk,variantKey:vk,status:'KILLED',failureStreak,market:d.market,candidate:spec,failureReason:'THREE_FAILED_GENERATIONS'});continue;}const tr=simulate(d.rows,d.prep,d.market,spec),a=metrics(tr.filter(x=>x.relativeIndex<TRAIN)),b=metrics(tr.filter(x=>x.relativeIndex>=TRAIN&&x.relativeIndex<VALID)),c=metrics(tr.filter(x=>x.relativeIndex>=VALID)),w=walk(tr),status=classify(a,b,c,w),reason=status==='PAPER_CANDIDATE'||status==='INTERESTING'?null:failureReason(a,b,c,w);results.push({hypothesisKey:hk,variantKey:vk,status,failureStreak:status==='DEAD'?failureStreak+1:0,failureReason:reason,market:d.market,candidate:spec,train:a,validation:b,holdout:c,walkForward:w});}
const rank={PAPER_CANDIDATE:4,INTERESTING:3,REGIME_DIVERGENCE:2,DEAD:1,KILLED:0};results.sort((x,y)=>rank[y.status]-rank[x.status]||((y.holdout?.expectancyBps??-999)-(x.holdout?.expectancyBps??-999)));const paper=results.filter(x=>x.status==='PAPER_CANDIDATE'),interesting=results.filter(x=>x.status==='INTERESTING'),divergence=results.filter(x=>x.status==='REGIME_DIVERGENCE'),rules=learningRules(results);const snapshot={ok:true,version:VERSION,mode:'RESEARCH_ONLY',paperOnly:true,liveOrders:false,executionAuthority:false,capitalEligible:false,completedAt:new Date().toISOString(),methodology:{barsPerMarket:MAX_BARS,symbols:SYMBOLS,timeframes:TIMEFRAMES,families:SPECS.map(x=>x.family),sessions:Object.keys(SESSIONS),killAfterFailures:3,classification:'train+validation consistency required for INTERESTING'},tested:results.filter(x=>x.status!=='KILLED').length,killed:results.filter(x=>x.status==='KILLED').length,interesting:interesting.length,regimeDivergence:divergence.length,paperCandidates:paper.length,verdict:paper.length?'PAPER_CANDIDATE_FOUND':interesting.length?'INTERESTING_EDGE_FOUND':divergence.length?'REGIME_DIVERGENCE_FOUND':'NO_EDGE_FOUND',top:results.filter(x=>x.status!=='KILLED').slice(0,12),nextGeneration:interesting.slice(0,8).map(x=>({parent:x.variantKey,mutation:`Mutate ${x.candidate.family} on ${x.market.pair} ${x.market.tf} ${x.candidate.session}; preserve costs and sealed holdout.`}))};
const learning={ok:true,version:'edge_learning_v1',paperOnly:true,liveOrders:false,executionAuthority:false,capitalEligible:false,completedAt:snapshot.completedAt,summary:{hypotheses:rules.length,paperCandidates:paper.length,interesting:interesting.length,regimeDivergence:divergence.length,killed:snapshot.killed},rules:rules.slice(0,24)};
await mkdir(dirname(out),{recursive:true});await writeFile(out,JSON.stringify(snapshot,null,2)+'\n');await appendFile(hist,JSON.stringify({...snapshot,results:results.map(x=>({hypothesisKey:x.hypothesisKey,variantKey:x.variantKey,status:x.status,failureReason:x.failureReason}))})+'\n');await writeFile(learningOut,JSON.stringify(learning,null,2)+'\n');await appendFile(learningHist,JSON.stringify(learning)+'\n');console.log(JSON.stringify({ok:true,verdict:snapshot.verdict,tested:snapshot.tested,interesting:snapshot.interesting,regimeDivergence:snapshot.regimeDivergence,paperCandidates:snapshot.paperCandidates}));}
main().catch(e=>{console.error(e);process.exitCode=1;});